config/routes.rb
Rails.application.routes.draw do


  get 'dashboards/show'

  devise_for :admins
  get '/dashboard/admins/new' => 'admins#new'
  post '/dashboard/admins/create' => 'admins#create'
  get '/dashboard/admins/edit' => 'admins#edit'
  delete '/dashboard/admins/:id' => 'admins#destroy'

  root 'questions#home'

  get '/' => 'questions#home'
  get '/dashboard' => 'dashboards#show'
  get '/dashboard/questions' => 'questions#index'
  get '/dashboard/questions/new' => 'questions#new'
  post '/dashboard/questions' => 'questions#create'

  get '/faq' => 'faqs#index', as: :faqs
  get '/dashboard/faqs' => 'faqs#faqs_dashboard'
  get '/dashboard/faqs/new' => 'faqs#new'
  post '/dashboard/faqs' => 'faqs#create'
  get '/dashboard/faqs/:id/edit' => 'faqs#edit'
  patch '/dashboard/faqs/:id' => 'faqs#update'
  delete '/dashboard/faqs/:id' => 'faqs#destroy'

  get '/questions/classic' => 'questions#classic'
  get '/questions/equitable' => 'questions#equitable'
  get '/questions' => 'questions#show'
  get '/dashboard/questions/:id/edit' => 'questions#edit'
  patch '/dashboard/questions/:id' => 'questions#update'
  delete '/dashboard/questions/:id' => 'questions#destroy'

  
  get '/dashboard/contents' => 'contents#index'
  get '/dashboard/contents/:id/edit' => 'contents#edit'
  patch '/dashboard/contents/:id' => 'contents#update'

  namespace :api do
    namespace :v1 do
      get '/questions' => 'questions#index'
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  validates :question_text, presence: true
  validates :answer_text, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :text, presence: true
  validates :no_response, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout "admin-application"
  # before_action :authenticate_admin!
  before_action :authenticate_superadmin!
  

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(
      email: params[:email],
      password: "defaulty",
      password_confirmation: "defaulty"  
    )

    if @admin.save
      email = params[:email]
      AdminNewMailer.admin_new(email).deliver_now
      flash[:success] = "Message sent"
      redirect_to '/dashboard'
    else
      redirect_to '/dashboard/admins/new'
    end
  end

  def edit
    @admins = Admin.all
  end

  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy  

    flash[:success] = "Admin removed"
    redirect_to '/dashboard'
  end
end

private

  def authenticate_superadmin!
      unless Admin.find_by(id: current_admin.id).superadmin
        redirect_to "/dashboard"
      end
  end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController

  def index
    @questions = Question.order(:id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  layout "admin-application"

  before_action :authenticate_admin!

  def index
    @contents = Content.all
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])
    if @content.update({text: params[:text], id: params[:id]})
    
      flash[:success] = "Content Edited"
      redirect_to '/dashboard/questions'
    else
      flash[:warning] = "Content not saved"
      render :edit
    end
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  layout "admin-application"
  before_action :authenticate_admin!

  def show
    @questions = Question.all
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  layout "admin-application", except: :index
  before_action :authenticate_admin!, except: :index

  def index
    @faqs = Faq.all
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new({
      question_text: params[:question_text],
      answer_text: params[:answer_text]
      })

    if @faq.save
      flash[:success] = "FAQ created!"
      redirect_to '/dashboard/faqs'
    else
      flash[:warning] = "FAQ was not created!"
      render :new
    end

  end

  def edit
    @faq = Faq.find_by(id: params[:id])
  end

  def update
    @faq = Faq.find_by(id: params[:id])
    if @faq.update({
      question_text: params[:question_text], 
      answer_text: params[:answer_text]
      })
      flash[:success] = "FAQ updated!"
      redirect_to "/dashboard/faqs"
    else
      flash[:warning] = "FAQ not updated. Please try again."
      render :edit
    end
  end

  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    flash[:success] = "FAQ deleted"
    redirect_to '/dashboard/faqs'
  end 

  def faqs_dashboard
    @faqs = Faq.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  layout "admin-application", except: [:show, :home, :classic, :equitable]

  def home

  end

  def index
    @questions = Question.all.order(:id)
    #admin user only
  end

  def show
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new({text: params[:text], yes_response: params[:yes_response], no_response: params[:no_response], prequalifier: params[:prequalifier]})
    session[:return_to] = request.referer

    if @question.save
      flash[:success] = "New question created"
      redirect_to '/dashboard/questions'
    else
      flash[:warning] = "Question not saved"
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end 

  def update
    @question = Question.find(params[:id])
    if @question.update({text: params[:text], yes_response: params[:yes_response], no_response: params[:no_response], prequalifier: params[:prequalifier], id: params[:id]})
    
      flash[:success] = "Question Edited"
      redirect_to '/dashboard/questions'
    else
      flash[:warning] = "Question not saved"
      render :edit
      # redirect_to request.referer
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = "Question deleted"
    redirect_to '/dashboard/questions'
  end 

  def classic
  end

  def equitable
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admins/edit.html.erb
<div class="container-fluid">
  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">Warning: deleting an admin account is not reversable!</h3>
        </div>
        <div class="panel-body">       
          <table style="width:80%" class="admin-table">
            <% @admins.each do |admin| %>
            <tr>
              <td id="email"><%= admin.email %></td>
              <td id="button"><%= link_to "Delete Admin", "#{admin.id}", class: "button-submit btn-lg", id: "button-submit", data: {confirm: "Deleting an admin account is not reversable.  Are you sure you want to delete #{admin.email}?"}, method: :delete %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<div class="container-fluid">
  <% if @admin.errors.any? %>
   <div class="alert alert-warning alert-dismissible" role="alert" id="error_explanation">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <p><b><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</b></p>

     <ul>
     <% @admin.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
</div>
<%= form_tag '/dashboard/admins/create', method: :post do %>
<div class="container-fluid">
  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">Create New Admin</h3>
        </div>
        <%= form_tag '/dashboard/admins/create' do %>
          <br>
          <%= text_field_tag :email, nil, placeholder: 'Enter email address...' %>
          <br>
          <br>
          <%= submit_tag "Create Admin", class: "button-submit btn-lg", id: "button-submit" %>

        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/contents/edit.html.erb
<%= form_tag "/dashboard/contents/#{@content.id}", method: :patch do %>
<div class="container-fluid">
  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">Edit <%= @content.content_type.capitalize %> Text</h3>
        </div>
        <div class="panel-body" id="question-text-body">
            <% label_tag :text %>
            <%= tinymce %>
            <%= text_area_tag :text, @content.text, :class => "tinymce", id: "question-text-field-tag" %>
        </div>
        
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="button-submit">
      <button type="submit" class="btn btn-default btn-lg" id="button-submit"><% submit_tag %>Save Changes</button>
    </div>
  </div>
</div>

<% end %>

app/views/contents/index.html.erb
<% @contents.each do |content| %>

  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title"><%= content.content_type.capitalize %> Text</h3>
        </div>
        <div class="panel-body textbox-border" id="question-text-body">       
            <%= raw content.text %>
        </div>
        <a href="/dashboard/contents/<%= content.id %>/edit" class="btn btn-default" id="button-edit" role="button">Edit Text</a>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<% @questions.each do |question| %>

  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">Question Text</h3>
        </div>
        <div class="panel-body textbox-border" id="question-text-body">       
            <%= raw question.text %>
        </div>
        <div class="question-response-field">
          <%= label_tag :yes_response %>:
          <%= question.yes_response %> &nbsp;
          <%= label_tag :no_response %>:
          <%= question.no_response %>
        </div>
        <a href="/dashboard/questions/<%= question.id %>/edit" class="btn btn-default" id="button-edit" role="button">Edit Question</a>
        <a href="/dashboard/questions/<%= question.id %>/" class="btn btn-default" role="button" id="button-delete" data-method="delete">Delete Question</a>
      </div>
    </div>
  </div>
<% end %>

app/views/faqs/_faq_form.html.erb
<div class="panel-body center">
  <div class="faq-box-title">
    <%= label_tag :question_text %>
    <%= tinymce %>
    <%= text_area_tag :question_text, @faq.question_text, :class=> "tinymce" %>
  </div>

  <div class="faq-box-title">
    <%= label_tag :answer_text %>
    <%= text_area_tag :answer_text, @faq.answer_text, :class=> "tinymce" %>
  </div>
</div>

      
    

app/views/faqs/edit.html.erb
<%= form_tag "/dashboard/faqs/#{@faq.id}", method: :patch do %>  
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="faq-text">
      <div class="panel panel-default faq-form-panel" id="faq-text-panel">
        <div class="panel-heading" id="faq-form-heading">
          <h3 class="panel-title faq-form-title">Edit FAQ Question</h3>
        </div>

        <%= render "faq_form" %>

      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="button-submit">
      <%= submit_tag "Update FAQ", class: "btn btn-default btn-lg faq-form-button-submit" %>
    </div>
  </div>
</div>

<% end %>

app/views/faqs/faqs_dashboard.html.erb
<% @faqs.each do |faq| %>

  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">FAQ Text</h3>
        </div>
        <div class="panel-body textbox-border" id="question-text-body">       
            <%= raw faq.question_text %>
        </div>

        <div class="panel-body textbox-border" id="question-text-body">       
            <%= raw faq.answer_text %>
        </div>
        <a href="/dashboard/faqs/<%= faq.id %>/edit" class="btn btn-default" id="button-edit" role="button">Edit FAQ</a>
        <a href="/dashboard/faqs/<%= faq.id %>" class="btn btn-default" role="button" id="button-delete" data-method="delete">Delete FAQ</a>
      </div>
    </div>
  </div>
<% end %>

app/views/faqs/index.html.erb
<div class="faqs-intro"><p>Based on your answers to our questions, it appears you do not qualify for "Innocent Spouse Relief" for taxes due. But, even if you do not qualify for Innocent Spouse Relief, do not worry! There are other options available that may provide you with tax relief.
<br>
<br>
Please review the eight frequently asked questions below to see which may apply to you. Then click on any questions you would like to see answers to for additional information, including next steps you can take to address federal income taxes the IRS claims you owe that you cannot afford to pay.</p></div>
<div class="container" id="faq-panel">

<% @faqs.each do |q|%>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading<%=q.id%>">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=q.id%>" aria-expanded="false" aria-controls="collapse<%=q.id%>" class="collapsed">
              <%= raw q.question_text %>
            </a>
          </h4>
        </div>

      <div id="collapse<%=q.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=q.id%>" aria-expanded="false" style="height: 0px;">
        <div class="panel-body">
          <%= raw q.answer_text %>
        </div>
      </div>
    </div>
  </div>

<% end %>

</div>

app/views/faqs/new.html.erb
<%= form_tag "/dashboard/faqs/#{@faq.id}", method: :post do %>  
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="faq-text">
      <div class="panel panel-default faq-form-panel" id="faq-text-panel">
        <div class="panel-heading" id="faq-form-heading">
          <h3 class="panel-title faq-form-title">New FAQ Question</h3>
        </div>

        <%= render "faq_form" %>

      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="button-submit">
      <%= submit_tag "Create FAQ", class: "btn btn-default btn-lg faq-form-button-submit" %>
    </div>
  </div>
</div>


<% end %>
  

app/views/layouts/admin-application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaxReliefApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
</head>
<body>

  <div class="header">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid" id="navbar-container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <%= image_tag "john-marshall-law-logo.png", class: "img-responsive" %>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
            <li><a href="/questions">Tax Relief Qualification</a></li>
            <li><%= link_to "Sign Out", "/admins/sign_out", method: :delete if admin_signed_in? %></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div class="container-fluid">

    <% flash.each do |name, message| %>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= message %>
      </div>
    <% end %>

    <div id="navbar-panel">
      <a href="/dashboard/questions" class="btn btn-default index-button" role="button">Questions</a>
      <a href="/dashboard/faqs" class="btn btn-default index-button" role="button">FAQs</a>
      <a href="/dashboard/questions/new" class="btn btn-default index-button" role="button">Create Question</a>
      <a href="/dashboard/faqs/new" class="btn btn-default index-button" role="button">Create FAQ</a>
      <% if Admin.find_by(id: current_admin.id).superadmin %>
        <a href="/dashboard/admins/new" class="btn btn-default index-button" role="button">Create Admin</a>
        <a href="/dashboard/admins/edit" class="btn btn-default index-button" role="button">Delete Admin</a>
      <% end %>
      <a href="/dashboard/contents" class="btn btn-default index-button" role="button">Success Contents</a>

    </div>

    <%= yield %>
  </div>

  <div class="footer">
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div class="container-fluid" id="navbar-container-footer">
        <div class="navbar-header" id="footer-text">
          <p>The John Marshall Law School Domestic Violence Clinic &copy 2017</p><p style="text-align:right;"></p>
        </div>
        <div class="navbar-right" id="footer-text">
          <p><a href="https://dalton.one" target="_blank">Dalton One Legal Technologies</a></p>
        </div>
      </div>
    </nav>
  </div>
 
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaxReliefApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
</head>
<body>

  <div class="header">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid" id="navbar-container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <%= image_tag "john-marshall-law-logo.png", class: "img-responsive" %>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
            <li><a href="/questions">Tax Relief Qualification</a></li>
            <% if admin_signed_in? %>
            <li><%= link_to "Admin Dashboard", "/dashboard" %></li>
            <% end %>
            <li><%= link_to "Sign Out", "/admins/sign_out", method: :delete if admin_signed_in? %></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  
  <div class="container-fluid">
    <div class="row">
      <div class="quick-close">
        <button type="button" class="btn btn-default btn-lg" id="large-button" style="position:fixed;left:10%;right:10%;z-index:1000;">Quick Close</button>
      </div>
    </div>
  </div>

  <%= yield %>

  <div class="footer">
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div class="container-fluid" id="navbar-container-footer">
        <div class="navbar-header" id="footer-text">
          <p>The John Marshall Law School Domestic Violence Clinic &copy 2017</p><p style="text-align:right;"></p>
        </div>
        <div class="navbar-right" id="footer-text">
          <p><a href="https://dalton.one" target="_blank">Dalton One Legal Technologies</a></p>
        </div>
      </div>
    </nav>
  </div>

</body>
</html>

app/views/questions/classic.html.erb
<div class="container">
  <div class="row">    
    <br>
    <%= raw Content.find_by(content_type: "classic").text %>
  </div>
</div>

app/views/questions/edit.html.erb
<%= form_tag "/dashboard/questions/#{@question.id}", method: :patch do %>
<div class="container-fluid">
  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">Edit Question Text</h3>
        </div>
        <div class="panel-body" id="question-text-body">
            <% label_tag :text %>
            <%= tinymce %>
            <%= text_area_tag :text, @question.text, :class => "tinymce", id: "question-text-field-tag" %>
        </div>
        <div class="question-response-field">
          <%= label_tag :yes_response %>
          <%= text_field_tag :yes_response, @question.yes_response,:id=> "yes-question-field-tag" %> &nbsp;
          <%= label_tag :no_response %>
          <%= text_field_tag :no_response, @question.no_response,:id=> "no-question-field-tag" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="button-submit">
      <button type="submit" class="btn btn-default btn-lg" id="button-submit"><% submit_tag %>Save Changes</button>
    </div>
  </div>
</div>

<% end %>

app/views/questions/equitable.html.erb
<div class="container">
  <div class="row">
    <br>
        <%= raw Content.find_by(content_type: "equitable").text %>
  </div>
</div>

app/views/questions/form.html.erb
<p>Based on your answers to these questions, it appears that you qualify to apply for “classic” innocent spouse relief under Section 6015 of the Internal Revenue Code. The IRS decision on whether to grant you relief from tax liability under the 'Innocent Spouse Relief' under the “classic” portion of the IRC is also based on how they view the equities of your situation and they will look at other facts too, such as if payment of these taxes would impose financial hardship to you.</p>

<p>See Form 8857, Request for Innocent Spouse Relief.</p>

<p>Form 8857: <a href="https://www.irs.gov/pub/irs-pdf/f8857.pdf">https://www.irs.gov/pub/irs-pdf/f8857.pdf</a></p>

<p>Form 8857 Instructions: https://www.irs.gov/pub/irs-pdf/i8857.pdf</p>

<p>Check back in the near future for an Interactive Form 8857 THAT the John Marshall Law School’s Domestic Violence Clinical Advocacy Program is currently working on. This interactive format will aid users in filling out the form. We will be creating tips on how to fill out IRS Form to show how you qualify to apply for Innocent Spouse Relief and how the equities of your situation should lead the IRS to grant this relief to you.</p>

<p>Also, if you are interested in obtaining help from the John Marshall Law School’s Family Law & Domestic Violence Clinic with any legal issues you may have relating to the abuse you have suffered from an intimate partner, these organizations will help connect you with our services.</p>

<p>Between Friends: http://www.betweenfriendschicago.org/aboutus.html</p>

<p>Chicago Children’s Advocacy Center: http://www.chicagocac.org/who-we-are/contact-us/</p>

<p>Family Rescue: http://www.familyrescueinc.org/ 
24-Hour Crisis Line: 800-360-6619
</p>

app/views/questions/index.html.erb
<div class="container-fluid">
  <div id="navbar-panel">
    <a href="/questions_index/new" class="btn btn-default index-button" role="button">Create Question</a>
    <a href="/faq/new" class="btn btn-default index-button" role="button">Create FAQ</a>
    <a href="/admins/new" class="btn btn-default index-button" role="button">Create Admin</a>
  </div>

<% @questions.each do |question| %>

  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">Question Text</h3>
        </div>
        <div class="panel-body textbox-border" id="question-text-body">       
            <%= raw question.text %>
        </div>
        <div class="question-response-field">
          <%= label_tag :yes_response %>:
          <%= question.yes_response %> &nbsp;
          <%= label_tag :no_response %>:
          <%= question.no_response %>
        </div>
        <a href="/questions_index/<%= question.id %>/edit" class="btn btn-default" id="button-edit" role="button">Edit Question</a>
        <a href="/questions_index/<%= question.id %>/" class="btn btn-default" role="button" id="button-delete" data-method="delete">Delete Question</a>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/questions/new.html.erb
<%= form_tag '/dashboard/questions', method: :post do %>
<div class="container-fluid">
  <div class="row" id="new-title">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="question-text">
      <div class="panel panel-default" id="question-text-panel">
        <div class="panel-heading" id="question-text-panel-heading">
          <h3 class="panel-title">New Question Text</h3>
        </div>
        

        <div class="panel-body" id="question-text-body">
            <% label_tag :text %>
            <%= tinymce %>
            <%= text_area_tag :text, @question.text, :class => "tinymce", id: "question-text-field-tag" %>
        </div>

        <div class="question-response-field">
          <%= label_tag :yes_response %>
          <%= text_field_tag :yes_response, @question.yes_response , id: "yes-question-field-tag" %> &nbsp;
          <%= label_tag :no_response %>
          <%= text_field_tag :no_response, @question.no_response , id: "no-question-field-tag" %>
        </div>
      </div>
    </div>
  </div>
<div class="container-fluid">
  <div class="row">
    <div class="button-submit">
      <%= submit_tag "Add New Question", class: "btn btn-default btn-lg", id: "button-submit" %>
    </div>
  </div>
</div>

<% end %>

app/views/questions/show.html.erb
<div ng-app="app">
  <br>
  <div ng-controller="questionsCtrl" ng-init="setup()" class="container">
    <div ng-repeat="question in questions track by $index">
       <div ng-show="question_index == $index">
          <p ng-bind-html="question.text">{{question.text}}</p>
          <a ng-click="checkYesResponse(question.yes_response)" class="btn btn-default">Yes</a>
          <a ng-click="checkNoResponse(question.no_response)" class="btn btn-default">No</a>
       </div>
    </div>

    <hr>

  </div>
 
</div>